
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: error

site:
  title: ThreatX Documentation
  start_page: txgeneral::landing.adoc
  robots: allow
  url: https://docs.threatx.com

content:
  sources:
    - url: https://github.com/ThreatX/threatx-docs-txprevent.git
      branches: ['1.0']
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-general.git
      branches: [main]
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-txprotect.git
      branches: ['3.20']
      start_path: docs

asciidoc:
  attributes:
      experimental: true
      copyright: '© Copyright 2024 ThreatX, Inc.'
      hide-uri-scheme: '@'
      idprefix: ''
      idseparator: '-'
      page-pagination: ''
      table-frame: 'none@'
      table-grid: 'rows@'
  extensions: [ ]

antora:
  extensions: 
    - '@antora/lunr-extension'
   
output:
  clean: true
  dir: ./public

ui:
  bundle:
    url: https://github.com/ThreatX/threatx-user-docs-ui-default/releases/download/0.1.2/ui-bundle.zip
    snapshot: true

