
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: error

site:
  title: ThreatX Documentation
  start_page: txgeneral::index.adoc
  robots: allow
  url: http://localhost:8080

content:
  sources:
    - url: ../threatx-docs-txprevent
      branches: HEAD
      start_path: docs
      edit_url: '{web_url}/{refname}/{path}'
    - url: ../threatx-docs-general
      branches: HEAD
      start_path: docs
      edit_url: '{web_url}/{refname}/{path}'
    - url: ../threatx-docs-txprotect
      branches: HEAD
      start_path: docs
      edit_url: '{web_url}/{refname}/{path}'

asciidoc:
  extensions:
    - asciidoctor-emoji
  attributes:
      experimental: true
      copyright: '© Copyright 2024 ThreatX, Inc.'
      hide-uri-scheme: '@'
      idprefix: ''
      idseparator: '-'
      page-pagination: ''
      table-frame: 'none@'
      table-grid: 'rows@'
      organization: ThreatX
      txprevent-current-version: '1.0'
      txprotect-current-version: '3.20'
    
antora:
  extensions: 
    - '@antora/pdf-extension'
    - '@antora/lunr-extension'
    - id: set-global-asciidoc-attributes
      enabled: true
      require: ./lib/set-global-asciidoc-attributes-extension.js
  

output:
  clean: true
  dir: ./public

ui:
  bundle:
    url: ../threatx-docs-ui/build/ui-bundle.zip
    snapshot: true

