
runtime:
  cache_dir: ./cache/antora
  log:
    failure_level: warn

site:
  title: ThreatX Product Documentation
  start_page: txprevent::index.adoc
  robots: allow
  url: https://docs.threatx.com

content:
  sources:
    - url: https://github.com/ThreatX/threatx-docs-txprevent.git
      branches: [main]
      start_path: docs

asciidoc:
  attributes:
      experimental: true
      copyright: '© Copyright 2024 ThreatX, Inc.'
      hide-uri-scheme: '@'
      idprefix: ''
      idseparator: '-'
      page-pagination: ''
      table-frame: 'none@'
      table-grid: 'rows@'
  extensions: [ ]
    
output:
  clean: true
  dir: ./public

ui:
  bundle:
    url: https://github.com/ThreatX/threatx-user-docs-ui-default/releases/download/0.1.1/ui-bundle.zip
    snapshot: true

