
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: error

site:
  title: ThreatX Documentation
  start_page: txgeneral::index.adoc
  robots: allow
  url: https://docs.threatx.com

content:
  sources:
    - url: https://github.com/ThreatX/threatx-docs-txprevent.git
      branches: ['1.1']
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-general.git
      branches: ['4.74']
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-txprotect.git
      branches: ['3.20']
      start_path: docs

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-emoji
  attributes:
      experimental: true
      hide-uri-scheme: '@'
      idprefix: ''
      idseparator: '-'
      page-pagination: ''
      table-frame: 'none@'
      table-grid: 'rows@'
      organization: ThreatX
      # Custom Attributes
      copyright: '© Copyright 2024 ThreatX, Inc.'
      txprevent-current-version: '1.1'
      txprotect-current-version: '3.20'
      txdashboard-current-version: '4.74'
      tip-caption: 💡 TIP
      caution-caption: 🔥 CAUTION
      note-caption: ℹ NOTE
      warning-caption: ⚠️ WARNING
      error-caption: ❌ ERROR
      important-caption: ❕ IMPORTANT   

antora:
  extensions: 
    - '@antora/pdf-extension'
    - '@antora/lunr-extension'
    - id: set-global-asciidoc-attributes
      enabled: true
      require: ./lib/set-global-asciidoc-attributes-extension.js
    - id: print-compiled-asciidoc-attributes
      enabled: true
      require: ./lib/print-compiled-asciidoc-attributes-extension.js
    - id: print-defined-asciidoc-attributes
      enabled: true
      require: ./lib/print-defined-asciidoc-attributes-extension.js
    - id: all-pages-report
      enabled: true
      require: ./lib/all-pages-report-extension.js
  
output:
  clean: true
  dir: ./public

ui:
  bundle:
    url: https://github.com/ThreatX/threatx-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true

