
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: error

site:
  title: ThreatX Documentation
  start_page: txgeneral::index.adoc
  robots: allow
  url: https://docs.threatx.com

content:
  sources:
    - url: https://github.com/ThreatX/threatx-docs-txprevent.git
      branches: ['1.0']
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-general.git
      branches: [main]
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-txprotect.git
      branches: ['3.20']
      start_path: docs

asciidoc:
  attributes:
      experimental: true
      :sectids:
      :sectlinks:
      hide-uri-scheme: '@'
      idprefix: ''
      idseparator: '-'
      page-pagination: ''
      table-frame: 'none@'
      table-grid: 'rows@'
      organization: ThreatX
      copyright: '© Copyright 2024 ThreatX, Inc.'
      txprevent-current-version: '1.0'
      txprotect-current-version: '3.20'
  extensions: [ ]

antora:
  extensions: 
    - '@antora/lunr-extension'
    - id: set-global-asciidoc-attributes
      enabled: true
      require: ./lib/set-global-asciidoc-attributes-extension.js
    - id: doc-to-pdf
      enabled: false
      require: ./lib/doc-to-pdf-extension.js
    - id: export-content
      enabled: false
      require: ./lib/export-content-extension.js
   
output:
  clean: true
  dir: ./public

ui:
  bundle:
    url: https://github.com/ThreatX/threatx-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true

