# 
# Antora site playbook - production
#  
runtime:
  fetch: true
  cache_dir: ./.cache/antora
  log:
    failure_level: error
    level: info
    format: pretty

site:
  title: ThreatX Documentation
  start_page: txgeneral::index.adoc
  robots: allow
  url: https://docs.threatx.com

urls:
  redirect_facility: static
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current

content:
  sources:
    - url: https://github.com/ThreatX/threatx-docs-txprevent.git
      branches: ['1.1', '1.2']
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-general.git
      branches: ['main']
      start_path: docs
    - url: https://github.com/ThreatX/threatx-docs-txprotect.git
      branches: ['3.20']
      start_path: docs

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-emoji
  attributes:
      #-----------------------
      # Asciidoctor attributes
      #-----------------------
      experimental: true
      # TOC
      toclevels: 4
      # Sections
      sectlinks: true
      sectanchors: true
      sectids: true
      # Fonts
      icons: font
      # Syntax highlighting
      source-highlighter: highlight.js
      # URIs
      hide-uri-scheme: '@'
      # anchors
      idprefix: ''
      idseparator: '-'
      # Tables
      table-frame: 'none@'
      table-grid: 'rows@'
      table-stripes: even
      # Captions 
      example-caption: 📌 Example
      tip-caption: 💡 TIP
      note-caption: 📒 NOTE
      warning-caption: ⚠️ WARNING
      caution-caption: 🔥 CAUTION
      error-caption:  ⁉️ERROR
      important-caption: ❕IMPORTANT
      # Organization details
      copyright: '© Copyright 2024 ThreatX, Inc.'
      orgname: ThreatX

      #------------------
      # Custom attributes
      #------------------
      organization: ThreatX
      # Versions
      txprevent-current-version: '1.2'
      txprotect-current-version: '3.20'
      # URLs
      url-txapi: 'https://api.threatx.com/tx_api/v2'
      # For Antora
      page-pagination: ''
      page-txprevent-current-version: '1.2'
      page-txprotect-current-version: '3.20'

antora:
  extensions: 
    - '@antora/pdf-extension'
    - '@antora/lunr-extension'
    - id: set-global-asciidoc-attributes
      enabled: true
      require: ./lib/set-global-asciidoc-attributes-extension.js
    - id: print-compiled-asciidoc-attributes
      enabled: true
      require: ./lib/print-compiled-asciidoc-attributes-extension.js
    - id: print-defined-asciidoc-attributes
      enabled: true
      require: ./lib/print-defined-asciidoc-attributes-extension.js
    - id: all-pages-report
      enabled: false
      require: ./lib/all-pages-report-extension.js
  
output:
  clean: true
  dir: ./public

ui:
  bundle:
    url: https://github.com/ThreatX/threatx-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true

