= ThreatX User Documentation Site and Playbook Project
:url-project: https://docs.threatx.io
:url-org: https://github.com/ThreatX
:url-repo: {url-org}/threatx-user-docs-site
:url-userdocs-playbook: {url-repo}/blob/main/antora-playbook.yml
:url-antora-docs: https://docs.antora.org
:url-docs-quickstart: {url-antora-docs}/install-and-run-quickstart/
:url-docs-playbook: {url-antora-docs}/playbook/
:url-docs-run: {url-antora-docs}/run-antora 

This is a playbook project for the ThreatX User Documentation site.

You can also use this project and the demo documentation components to generate the demo site on your own computer
To use the demo materials and generate the demo site locally, follow the steps in the {url-docs-quickstart}[Antora quickstart].

== Antora Playbook

An {url-docs-playbook}[Antora playbook] is responsible for generating a documentation site.
It contains the instructions a user wants to relay to the Antora site generator.
These instructions include the content Antora should collect and the UI it should apply to the generated site.

The file [.path]_antora-playbook.yml_ in this repository is the playbook used to produce the demo site.
It tells Antora where to find the Component A and Component B remote content repositories and default UI.

== Generate the Demo Site

After cloning this playbook project repository to your computer or setting up your own playbook for the demo site (see the {url-docs-quickstart}[Antora quickstart] for instructions) you can generate the demo site by {url-docs-run}[running Antora].

