name: Generate

on:
  workflow_dispatch:
  push:

jobs:

  build:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [22.8.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Install Ruby
      run: |
        sudo apt-get update && sudo apt-get install -y software-properties-common
        sudo apt-add-repository -y ppa:rael-gc/rvm
        sudo apt-get update && sudo apt-get install -y rvm
        source /etc/profile.d/rvm.sh
        rvm install 3.3.5
        rvm use 3.3.5
        bundle config set path '.bundle/gems'
        bundle 

    - name: Install Node Dependencies 
      run: npm install
    
    - name: Generate Site 
      env:
       CI: false
      run: |
        source /etc/profile.d/rvm.sh
        rvm use 3.3.5
        ./node_modules/.bin/antora --fetch --stacktrace antora-playbook.yml
        ls public  
        
    - name: Upload Site Files Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: public
        path: public/*
        if-no-files-found: error
