#name: Build and Deploy Site

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.8.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Install Dependencies 
      run: |
          npm install
    
    - name: Generate Site (Antora)
      run: |
        npx antora --fetch --stacktrace antora-playbook.yml
        ls public
      
    - name: Upload Site to S3 
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
          AWS_S3_BUCKET: docs.threatx.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' 
          SOURCE_DIR: 'public'      
        
    - name: Upload Site Files Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: public
        path: public/*
        if-no-files-found: error
