# This is a basic workflow that is manually triggered

name: Stage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/generate.yml
    
  stage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    steps:
    - name: Download build artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: generate.yml
    
    - name: Upload site
      uses: bwcxyk/s3-sync-action@1.0.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ vars.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        SOURCE_DIR: 'public'   
