---

name: Validate

on:
  workflow_dispatch:
    inputs:
      target_url:
        type: choice
        description: Site to check
        options: 
        - https://docs.threatx.com
        - https://docs-staging.threatx.com
        default: 'https://docs.threatx.com'
  workflow_run:
    workflows:
      - Publish
    types:
      - completed
    branches: 
      - main

jobs:
   
   check-links: 
     runs-on: ubuntu-latest
     steps:
       - name: Check Links
         uses: filiph/linkcheck@2.0.23
         with:
           arguments:  ${{ github.event.inputs.target_url || 'https://docs.threatx.com' }}


 
