---

name: Validate

on:
  workflow_dispatch:
  workflow_call:


jobs:
  quality:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Links
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://docs.threatx.com


 
