---

name: Validate

on:
  workflow_dispatch:
    inputs:
      target_url:
        type: choice
        description: Site to check
        options: 
        - https://docs.threatx.com
        - http://docs-staging.threatx.com
        default: 'https://docs.threatx.com'
  workflow_run:
    workflows:
      - Publish
    types:
      - completed
    branches: 
      - main

jobs:
       
   check-links: 
     runs-on: ubuntu-latest
     steps:
       - run: echo "Publish workflow was a success"
       - name: Check Links
         uses: filiph/linkcheck@2.0.23
         with:
           arguments: ${{ inputs.target_url }}


 
